services:
  frontend:
    build: ./democrachat-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
  backend:
    build: ./Democrachat
    environment:
      CUSTOMCONNSTR_Default: "Host=postgres;Database=democrachat;Username=postgres;Password=CHANGETHIS;"
    depends_on: 
      - postgres
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: democrachat
      POSTGRES_PASSWORD: CHANGETHIS
    volumes:
      - dcpg:/var/lib/postgresql/data
  peer:
    image: peerjs/peerjs-server
    ports:
      - "9000:9000"
    command: peerjs -p 9000 --path / --proxied
  
volumes:
  dcpg: 
    external: true
