services:
  frontend:
    image: democrachat_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
  backend:
    image: democrachat_backend
    environment:
      CUSTOMCONNSTR_Default: "Host=postgres;Database=democrachat;Username=postgres;Password=CHANGETHIS;"
    depends_on: 
      - postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: democrachat
      POSTGRES_PASSWORD: CHANGETHIS
    volumes:
      - dcpg:/var/lib/postgres/data
  peer:
    image: peerjs/peerjs-server
    ports:
      - "8081:9000" # Should be exposed behind reverse proxy on port 9000
    command: peerjs -p 9000 --path / --proxied
  
volumes:
  dcpg:
